### ISSUE TITLE
[BUG]Cursor not support.

### ISSUE THREAD

**Issue by 60999** [wmerkens/vscode-circuitpython#9]
[Window Title]
Cursor

[Content]
无法安装“wmerkens.vscode-circuitpython-v2”扩展，因为它与当前 Cursor 版本不兼容(版本 0.43.5)。

[确定(O)]

-----
Thanks for your work at circuitpython.

**Comment by wmerkens** [comment]
I'm sorry, but the extension was written for VSC and not for any derivates. I did test it against Eclipse New Theo, and it failed there, too. So, this extension will only work in standard VSC for the foreseeable future. I will update the readme to reflect this.

**Comment by SAK917** [comment]
Hi Will,

First and foremost, thanks for taking this on... I am very appreciative to see this extension getting much-needed updates!

I know this issue is closed, but I wanted to ask if the fix might be as simple as relaxing the version requirement for vscode in package.json?  With your current release (v0.3.0) of the vscode-circuitpython extension, the vscode version requirement in package.json is "^1.96.2" (which is the currently released version of VSCode as of 12/23/2024), while the vscode version in the current release of Cursor is 1.93.1.

I am sorry that I am too unfamiliar with VSCode extensions and TypeScript to understand how to try making a change to the vscode version requirement and build a new version of the extension to test it, but wanted to ask if this could be the reason for the "Error: Unable to install extension 'wmerkens.vscode-circuitpython-v2' as it is not compatible with VS Code '1.93.1'." message I get when trying to install this extension in Cursor?  And if so, is it possible to relax the vscode version requirement for this extension?

**Comment by wmerkens** [comment]
Yes, I can relax the version of VSC, but that won't help. Other core parts were brought up to date, and the NPM modules won't like it because they must also be downgraded.

Please look at this comparison of the Cursor I just downloaded and the current VSC.

![Screenshot 2024-12-23 034042](https://github.com/user-attachments/assets/387ae1e1-03e0-4286-9756-66c3202f04e6)

Notice that Electron, Chromium, and Node.js are all behind.

The real kicker is Electron, if it gets behind you get weird NPM/Node errors in the modules.

I spent a bit of time carefully updating the extension, and there are still 4 NPM modules that I cannot update because VSC cannot handle even more modern NPM/Node.js 

Node.js is currently set to LTS version 20.18. If this version was too old, I started getting errors on NPM packages in Windows, which complained that they were missing packages in VSC.

According to the VSC suggestions on developing extensions, I need to keep parity with VSC and the versions of NPM and Node.js it uses.

Cursor needs to update itself; it is way behind. According to the version of VSCode, it has been about a year.

I would have to start a whole branch just for Cursor support, I will roll a custom vsix file with a change to VSCode but I don't know if that will be enough for it to work.

**Comment by wmerkens** [comment]
Ok, I have created a branch for Cursor AI. I have added to the MS VSC Marketplace an entry for Cursor AI called

CircuitPython V2 Cursor AI

I have tested (basic tests) in Linux and Windows.

**Comment by SAK917** [comment]
Will, I just loaded your new CP release for Cursor with no issues and it is working great, thank you!  I am sorry my ignorance led to more work for you, and given how much work this ultimately was you went way above and beyond, especially doing it so quickly.   I sincerely appreciate this early Christmas present, and If there is anything I can do to help with the development or maintenance of this project, please don't hesitate to ask.
